apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::473823228351:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13Q99CSZHRO1E
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::473823228351:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-18T20:10:54Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-18T20:10:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1572"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 93ca7bdc-db28-4308-8958-99e8a2922f11
