apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::473823228351:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-G9IYATDZLSVG
      username: system:node:{{EC2PrivateDNSName}}
      - rolearn: arn:aws:iam::473823228351:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-16T10:40:12Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-16T10:40:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1495"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7b69e36d-7511-4af1-aef6-9cc7e975291b

