apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::473823228351:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1FA8NGK228P3B
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::473823228351:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-17T10:46:51Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-17T10:46:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1485"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dc04f36a-ca4a-4ba0-8ea3-1b9580151a10
